Repository Coconut-Finance-Team/Coconut-Project, pull requests merged in 2024-11, with the labels that each got.

#9 feat(#8): gitignore 설정 파일 은닉
  Coconut-Backend/.gitignore
Labels: BE

#24 Feat-공모주 UI개선 및 청약조회 페이지 구현
  Coconut-Frontend/package-lock.json
  Coconut-Frontend/package.json
  Coconut-Frontend/src/App.js
  Coconut-Frontend/src/components/common/Header.js
  Coconut-Frontend/src/components/subscription/Subscription.js
  Coconut-Frontend/src/components/subscription/SubscriptionApply.js
  Coconut-Frontend/src/components/subscription/SubscriptionCalendar.css
  Coconut-Frontend/src/components/subscription/SubscriptionComplete.js
  Coconut-Frontend/src/components/subscription/SubscriptionConfirm.js
  Coconut-Frontend/src/components/subscription/SubscriptionInquiry.js
  Coconut-Frontend/src/components/subscription/SubscriptionTable.js
Labels: FE, design

#29 feat #28: 프론트(코스피 및 코스닥 구현, 계좌관리 구현, 종목정보 구현)
  Coconut-Frontend/package-lock.json
  Coconut-Frontend/package.json
  Coconut-Frontend/src/App.js
  Coconut-Frontend/src/components/Account.js
  Coconut-Frontend/src/components/account/AccountManage.js
  Coconut-Frontend/src/components/account/AccountSidebar.js
  Coconut-Frontend/src/components/account/AssetLog.js
  Coconut-Frontend/src/components/account/OrderLog.js
  Coconut-Frontend/src/components/account/Sales.js
  Coconut-Frontend/src/components/account/TransactionLog.js
  Coconut-Frontend/src/components/account/modal/ModalOverlay.js
  Coconut-Frontend/src/components/account/modal/PwChangeModal.js
  Coconut-Frontend/src/components/account/modal/RightModal.js
  Coconut-Frontend/src/components/account/modal/TerminationModal.js
  Coconut-Frontend/src/components/auth/FindIdPassword.js
  Coconut-Frontend/src/components/auth/Login.js
  Coconut-Frontend/src/components/auth/Signin.js
  Coconut-Frontend/src/components/auth/SigninAddInfo.js
  Coconut-Frontend/src/components/auth/SigninUserInfo.js
  Coconut-Frontend/src/components/common/Header.js
  Coconut-Frontend/src/components/common/SearchPage.js
  Coconut-Frontend/src/components/home/ChartDetail.js
  Coconut-Frontend/src/components/home/IndexChart.js
  Coconut-Frontend/src/components/home/RealTimeChart.js
  Coconut-Frontend/src/components/home/StockDetail.js
  Coconut-Frontend/src/components/subscription/SubscriptionTable.js
Labels: FE, design

#32 feat-KIS 종목 시세 데이터 websocket 실시간으로 받기
  Coconut-Backend/build.gradle
  Coconut-Backend/src/main/java/com/coconut/stock_app/config/ApiConfig.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/config/SecurityConfig.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/controller/StockController.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/KISApiService.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/KISWebSocketClient.java
  Coconut-Backend/src/test/java/com/coconut/stock_app/service/WebSocketKeyServiceTest.java
Labels: BE, question, work in progress

#33 feat-실시간종목데이터파싱 및 mysql 저장
  Coconut-Backend/src/main/java/com/coconut/stock_app/dto/StockChartDTO.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/repository/cloud/StockRepository.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/KISWebSocketClient.java
Labels: BE, feature, work in progress

#35 Feat-프론트 종목정보 캔들차트 구현re
  Coconut-Frontend/package-lock.json
  Coconut-Frontend/package.json
  Coconut-Frontend/src/components/Account.js
  Coconut-Frontend/src/components/home/StockChart.js
  Coconut-Frontend/src/components/home/StockDetail.js
Labels: FE, design

#42 fix-다중 웹소켓 통합
  Coconut-Backend/src/main/java/com/coconut/stock_app/controller/StockController.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/dto/StockChartDTO.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/entity/cloud/StockChart.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/KISIndexWebSocketClient.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/KISWebSocketClient.java
Labels: bug, BE

#44 feat: 분봉 차트 생성
  Coconut-Frontend/package-lock.json
  Coconut-Frontend/src/components/home/StockChart.js
  Coconut-Frontend/src/components/home/StockDetail.js
Labels: FE, design, feature

#94 Feat : 프론트엔드 내 계좌 API 연동 및 매수/매도 연동
  Coconut-Backend/src/main/java/com/coconut/stock_app/controller/AccountController.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/impl/AccountServiceImpl.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/impl/TradeServiceImpl.java
  Coconut-Frontend/package-lock.json
  Coconut-Frontend/package.json
  Coconut-Frontend/src/App.js
  Coconut-Frontend/src/components/Account.js
  Coconut-Frontend/src/components/account/AccountManage.js
  Coconut-Frontend/src/components/account/AssetLog.js
  Coconut-Frontend/src/components/account/AssetSummary.js
  Coconut-Frontend/src/components/account/OrderLog.js
  Coconut-Frontend/src/components/account/Sales.js
  Coconut-Frontend/src/components/account/SubscriptionHistory.js
  Coconut-Frontend/src/components/account/TransactionLog.js
  Coconut-Frontend/src/components/account/createAccount/CreateAccountModal.js
  Coconut-Frontend/src/components/account/createAccount/Steps/Step2Terms.js
  Coconut-Frontend/src/components/account/createAccount/Steps/Step3Identity.js
  Coconut-Frontend/src/components/account/createAccount/Steps/Step4AccountType.js
  Coconut-Frontend/src/components/account/createAccount/Steps/Step5Password.js
  Coconut-Frontend/src/components/account/createAccount/Steps/Step6Complete.js
  Coconut-Frontend/src/components/admin/pages/Dashboard.js
  Coconut-Frontend/src/components/admin/pages/MonthlyReport.js
  Coconut-Frontend/src/components/admin/pages/SystemMonitoring.js
  Coconut-Frontend/src/components/admin/pages/UserDetail.js
  Coconut-Frontend/src/components/admin/pages/UserManagement.js
  Coconut-Frontend/src/components/auth/Login.js
  Coconut-Frontend/src/components/auth/SigninAddInfo.js
  Coconut-Frontend/src/components/common/Header.js
  Coconut-Frontend/src/components/home/StockDetail.js
  Coconut-Frontend/src/components/mypage.js
  Coconut-Frontend/src/components/subscription/Subscription.js
  Coconut-Frontend/src/components/subscription/SubscriptionComplete.js
  Coconut-Frontend/src/components/subscription/SubscriptionConfirm.js
  Coconut-Frontend/src/components/subscription/SubscriptionTable.js
  Coconut-Frontend/yarn.lock
Labels: FE, design

#99 Kospi/Kosdaq 차트 구현
  Coconut-Backend/src/main/java/com/coconut/stock_app/repository/cloud/StockChartRepository.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/StockSearchService.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/impl/AccountServiceImpl.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/service/impl/StockSearchServiceImpl.java
  Coconut-Backend/src/main/java/com/coconut/stock_app/websocket/StockInitializer.java
Labels: FE, feature

#101 feat-검색 기능 연동, 주식 차트 UI 수정
  Coconut-Frontend/src/components/common/SearchPage.js
  Coconut-Frontend/src/components/home/StockDetail.js
  Coconut-Frontend/src/components/home/StockDetailStyles.js
Labels: FE, design, feature
